In [1]:
#check whether the champions and boundary cases are the same when using HistGradientBoosting:

In [1]:
import pandas as pd
import pm4py

In [2]:
#Sepsis:

In [2]:
sepsis_log=pm4py.read_xes("./Data/sepsis/sepsis.xes")

c:\Users\ccagu\anaconda3\envs\naturalexamples\lib\site-packages\pm4py\util\dt_parsing\parser.py:77: UserWarning: ISO8601 strings are not fully supported with strpfromiso for Python versions below 3.11
  warnings.warn(
c:\Users\ccagu\anaconda3\envs\naturalexamples\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
parsing log, completed traces :: 100%|██████████| 1050/1050 [00:01<00:00, 1000.25it/s]

In [3]:
folderName="declare_rules-histGradient-05-30-2026_13-55-14"

In [4]:
pd.read_csv("./results/Ours/sepsis/"+folderName+"/best_predicted_instance_classSIRS-False.csv")

,case:concept:name,'Absence(Admission IC)','Absence(Admission NC)','Absence(CRP)','Absence(ER Registration)','Absence(ER Sepsis Triage)','Absence(ER Triage)','Absence(IV Antibiotics)','Absence(IV Liquid)','Absence(LacticAcid)',...,"'Succession(Return ER, ER Triage)'","'Succession(Return ER, IV Antibiotics)'","'Succession(Return ER, IV Liquid)'","'Succession(Return ER, LacticAcid)'","'Succession(Return ER, Leucocytes)'","'Succession(Return ER, Release A)'","'Succession(Return ER, Release B)'","'Succession(Return ER, Release C)'","'Succession(Return ER, Release D)'","'Succession(Return ER, Release E)'"
0,Q,100.0,100.0,100.0,0.0,0.0,0.0,100.0,100.0,100.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sepsis_log[sepsis_log["case:concept:name"]=="Q"]["concept:name"]

186     ER Registration
187           ER Triage
188    ER Sepsis Triage
Name: concept:name, dtype: object

In [6]:
pd.read_csv("./results/Ours/sepsis/"+folderName+"/best_predicted_instance_classSIRS-True.csv")

,case:concept:name,'Absence(Admission IC)','Absence(Admission NC)','Absence(CRP)','Absence(ER Registration)','Absence(ER Sepsis Triage)','Absence(ER Triage)','Absence(IV Antibiotics)','Absence(IV Liquid)','Absence(LacticAcid)',...,"'Succession(Return ER, ER Triage)'","'Succession(Return ER, IV Antibiotics)'","'Succession(Return ER, IV Liquid)'","'Succession(Return ER, LacticAcid)'","'Succession(Return ER, Leucocytes)'","'Succession(Return ER, Release A)'","'Succession(Return ER, Release B)'","'Succession(Return ER, Release C)'","'Succession(Return ER, Release D)'","'Succession(Return ER, Release E)'"
0,HEA,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,33.333333,0.0,NaN,NaN,NaN,NaN

In [7]:
sepsis_log[sepsis_log["case:concept:name"]=="HEA"]["concept:name"]

11749     ER Registration
11750           ER Triage
11751    ER Sepsis Triage
11752           IV Liquid
11753                 CRP
11754          Leucocytes
11755          LacticAcid
11756      IV Antibiotics
11757        Admission NC
11758          Leucocytes
11759                 CRP
11760                 CRP
11761          Leucocytes
11762          Leucocytes
11763                 CRP
11764           Release A
11765           Return ER
11766                 CRP
11767          Leucocytes
Name: concept:name, dtype: object

In [8]:
bc_sepsis_hist=pd.read_csv("./results/Ours/sepsis/"+folderName+"/boundaryCases_ClassesSIRS-False-SIRS-True.csv")

In [9]:
sepsis_dataset=pd.read_csv("./Data/sepsis/mined_sepsis_confidences_SIRS2OrMore.csv")

In [10]:
sepsis_dataset[sepsis_dataset["case:concept:name"]==bc_sepsis_hist["case:concept:name"][0]]["Class"]

443    SIRS-False
Name: Class, dtype: object

In [11]:
sepsis_log[sepsis_log["case:concept:name"]==bc_sepsis_hist["case:concept:name"][0]]["concept:name"]

6163     ER Registration
6164           ER Triage
6165    ER Sepsis Triage
6166          LacticAcid
6167          Leucocytes
6168                 CRP
6169        Admission NC
6170        Admission NC
6171                 CRP
6172          Leucocytes
6173           Release A
Name: concept:name, dtype: object

In [34]:
sepsis_log[sepsis_log["case:concept:name"]==bc_sepsis_hist["case:concept:name"][1]]["concept:name"]

14210     ER Registration
14211           ER Triage
14212    ER Sepsis Triage
14213          LacticAcid
14214          Leucocytes
14215                 CRP
14216        Admission NC
14217                 CRP
14218          Leucocytes
14219           Release A
Name: concept:name, dtype: object

In [13]:
###########################################################################################################################################################################################

In [13]:
rtfm_log=pm4py.read_xes("./Data/road_traffic/Road_Traffic_Fine_Management_Process.xes")

parsing log, completed traces :: 100%|██████████| 150370/150370 [01:02<00:00, 2420.25it/s]

In [14]:
route_RTFM="declare_rules-histGradient-05-30-2026_14-01-58"

In [15]:
prototype_collected=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/best_predicted_instance_classcollected.csv")

In [16]:
prototype_collected["case:concept:name"][0]

'A2512'

In [17]:
rtfm_log[rtfm_log["case:concept:name"]==prototype_collected["case:concept:name"][0]]

,amount,org:resource,dismissal,concept:name,vehicleClass,totalPaymentAmount,lifecycle:transition,time:timestamp,article,points,case:concept:name,expense,notificationType,lastSent,paymentAmount,matricola
31515,35.0,558,NIL,Create Fine,A,0.0,complete,2006-09-04 00:00:00+00:00,157.0,0.0,A2512,NaN,NaN,NaN,NaN,NaN
31516,NaN,NaN,NaN,Send Fine,NaN,NaN,complete,2006-12-15 00:00:00+00:00,NaN,NaN,A2512,22.0,NaN,NaN,NaN,NaN
31517,NaN,NaN,NaN,Insert Fine Notification,NaN,NaN,complete,2006-12-23 00:00:00+00:00,NaN,NaN,A2512,NaN,P,P,NaN,NaN
31518,71.5,NaN,NaN,Add penalty,NaN,NaN,complete,2007-02-21 00:00:00+00:00,NaN,NaN,A2512,NaN,NaN,NaN,NaN,NaN
31519,NaN,NaN,NaN,Notify Result Appeal to Offender,NaN,NaN,complete,2007-10-06 00:00:00+00:00,NaN,NaN,A2512,NaN,NaN,NaN,NaN,NaN
31520,NaN,NaN,NaN,Receive Result Appeal from Prefecture,NaN,NaN,complete,2007-10-06 00:00:00+00:00,NaN,NaN,A2512,NaN,NaN,NaN,NaN,NaN
31521,NaN,NaN,NaN,Send for Credit Collection,NaN,NaN,complete,2009-03-30 00:00:00+00:00,NaN,NaN,A2512,NaN,NaN,NaN,NaN,NaN

In [18]:
prototype_dismissed=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/best_predicted_instance_classdismissed.csv")

In [19]:
rtfm_log[rtfm_log["case:concept:name"]==prototype_dismissed["case:concept:name"][0]]["concept:name"]

544865                              Create Fine
544866                                Send Fine
544867                 Insert Fine Notification
544868                              Add penalty
544869         Insert Date Appeal to Prefecture
544870    Receive Result Appeal from Prefecture
544871         Notify Result Appeal to Offender
544872                          Appeal to Judge
Name: concept:name, dtype: object

In [20]:
prototype_fully_paid=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/best_predicted_instance_classfully_paid.csv")

In [21]:
rtfm_log[rtfm_log["case:concept:name"]==prototype_fully_paid["case:concept:name"][0]]["concept:name"]

490266    Create Fine
490267        Payment
490268      Send Fine
490269        Payment
Name: concept:name, dtype: object

In [22]:
prototype_unresolved=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/best_predicted_instance_classunresolved.csv")

In [23]:
rtfm_log[rtfm_log["case:concept:name"]==prototype_unresolved["case:concept:name"][0]]["concept:name"]

162524    Create Fine
162525      Send Fine
Name: concept:name, dtype: object

In [24]:
bc_histgradient_dismissed_unresolved=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/boundaryCases_Classesdismissed-unresolved.csv")

In [25]:
dataset_rtfm=pd.read_csv("./Data/road_traffic/mined_rtfm_relabelled_confidences.csv")

In [26]:
bc_histgradient_dismissed_unresolved

,case:concept:name,"'AlternatePrecedence(Payment, Send for Credit Collection)'","'ChainResponse(Send Fine, Insert Fine Notification)'","'ChainResponse(Add penalty, Receive Result Appeal from Prefecture)'","'NotChainResponse(Send Appeal to Prefecture, Receive Result Appeal from Prefecture)'","'AlternatePrecedence(Insert Date Appeal to Prefecture, Send for Credit Collection)'","'AlternateResponse(Insert Date Appeal to Prefecture, Add penalty)'","'ChainPrecedence(Notify Result Appeal to Offender, Payment)'","'NotChainResponse(Insert Fine Notification, Appeal to Judge)'","'NotChainResponse(Send Fine, Send Appeal to Prefecture)'",...,"'AlternatePrecedence(Insert Fine Notification, Insert Date Appeal to Prefecture)'","'ChainResponse(Insert Date Appeal to Prefecture, Send Fine)'","'ChainResponse(Send Fine, Send Appeal to Prefecture)'","'NotChainPrecedence(Receive Result Appeal from Prefecture, Send Appeal to Prefecture)'","'NotPrecedence(Insert Fine Notification, Payment)'","'NotChainResponse(Send Fine, Appeal to Judge)'","'NotResponse(Notify Result Appeal to Offender, Appeal to Judge)'","'ChainResponse(Insert Date Appeal to Prefecture, Appeal to Judge)'","'NotPrecedence(Appeal to Judge, Send Appeal to Prefecture)'","'NotChainPrecedence(Receive Result Appeal from Prefecture, Payment)'"
0,S73115,-100.0,0.0,-100.0,100.0,-100.0,0.0,-100.0,-100.0,100.0,...,0.0,0.0,0.0,100.0,-100.0,100.0,-100.0,0.0,100.0,-100.0
1,N82103,-100.0,100.0,0.0,0.0,-100.0,100.0,-100.0,100.0,100.0,...,100.0,0.0,0.0,100.0,-100.0,100.0,0.0,0.0,100.0,-100.0

In [27]:
dataset_rtfm[dataset_rtfm["case:concept:name"]==bc_histgradient_dismissed_unresolved["case:concept:name"][0]]["Class"]

132855    dismissed
Name: Class, dtype: object

In [28]:
rtfm_log[rtfm_log["case:concept:name"]==bc_histgradient_dismissed_unresolved["case:concept:name"][0]]

,amount,org:resource,dismissal,concept:name,vehicleClass,totalPaymentAmount,lifecycle:transition,time:timestamp,article,points,case:concept:name,expense,notificationType,lastSent,paymentAmount,matricola
489389,32.0,839,NIL,Create Fine,A,0.0,complete,2002-06-08 00:00:00+00:00,158.0,0.0,S73115,NaN,NaN,NaN,NaN,NaN
489390,NaN,NaN,NaN,Send Fine,NaN,NaN,complete,2002-07-29 00:00:00+00:00,NaN,NaN,S73115,10.0,NaN,NaN,NaN,NaN
489391,NaN,NaN,NaN,Insert Date Appeal to Prefecture,NaN,NaN,complete,2002-09-11 00:00:00+00:00,NaN,NaN,S73115,NaN,NaN,NaN,NaN,NaN
489392,NaN,NaN,#,Send Appeal to Prefecture,NaN,NaN,complete,2002-09-30 00:00:00+00:00,NaN,NaN,S73115,NaN,NaN,NaN,NaN,NaN

In [29]:
rtfm_log[rtfm_log["case:concept:name"]==bc_histgradient_dismissed_unresolved["case:concept:name"][1]]

,amount,org:resource,dismissal,concept:name,vehicleClass,totalPaymentAmount,lifecycle:transition,time:timestamp,article,points,case:concept:name,expense,notificationType,lastSent,paymentAmount,matricola
236999,35.0,541,NIL,Create Fine,A,0.0,complete,2005-08-01 00:00:00+00:00,157.0,0.0,N82103,NaN,NaN,NaN,NaN,NaN
237000,NaN,NaN,NaN,Send Fine,NaN,NaN,complete,2006-02-14 00:00:00+00:00,NaN,NaN,N82103,22.0,NaN,NaN,NaN,NaN
237001,NaN,NaN,NaN,Insert Fine Notification,NaN,NaN,complete,2006-02-23 00:00:00+00:00,NaN,NaN,N82103,NaN,P,P,NaN,NaN
237002,NaN,NaN,NaN,Insert Date Appeal to Prefecture,NaN,NaN,complete,2006-03-23 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,NaN
237003,71.5,NaN,NaN,Add penalty,NaN,NaN,complete,2006-04-24 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,NaN
237004,NaN,NaN,NIL,Send Appeal to Prefecture,NaN,NaN,complete,2006-05-18 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,NaN
237005,NaN,NaN,NaN,Receive Result Appeal from Prefecture,NaN,NaN,complete,2006-07-04 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,NaN
237006,NaN,NaN,NaN,Notify Result Appeal to Offender,NaN,NaN,complete,2006-07-08 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,NaN
237007,NaN,0,NIL,Appeal to Judge,NaN,NaN,complete,2006-08-08 00:00:00+00:00,NaN,NaN,N82103,NaN,NaN,NaN,NaN,0.0

In [30]:
bc_histgradient_fullypaid_unresolved=pd.read_csv("./results/Ours/rtfm/"+route_RTFM+"/boundaryCases_Classesfully_paid-unresolved.csv")

In [31]:
dataset_rtfm[dataset_rtfm["case:concept:name"]==bc_histgradient_fullypaid_unresolved["case:concept:name"][0]]["Class"]

91783    fully_paid
Name: Class, dtype: object

In [32]:
rtfm_log[rtfm_log["case:concept:name"]==bc_histgradient_fullypaid_unresolved["case:concept:name"][0]]["concept:name"]

340026                 Create Fine
340027                   Send Fine
340028    Insert Fine Notification
340029                 Add penalty
340030             Appeal to Judge
340031                     Payment
340032                     Payment
340033                     Payment
340034                     Payment
Name: concept:name, dtype: object

In [33]:
rtfm_log[rtfm_log["case:concept:name"]==bc_histgradient_fullypaid_unresolved["case:concept:name"][1]]["concept:name"]

282434                 Create Fine
282435                   Send Fine
282436    Insert Fine Notification
282437             Appeal to Judge
282438                 Add penalty
282439                     Payment
Name: concept:name, dtype: object